# ════════════════════════════════════════════════════════════════
# OZI BOT — База данных образовательных центров Астаны
# ⚠️ ВНИМАНИЕ: сейчас это ДЕМО-ДАННЫЕ (телефоны и цены вымышленные).
# Перед публичным запуском каждый центр заменить реальными данными
# из верификационных визитов/звонков Чингиза.
# Верифицирована командой OZI | Июль 2026
# ════════════════════════════════════════════════════════════════

CENTERS = [
    # ─────────── АНГЛИЙСКИЙ ЯЗЫК ───────────────────────────────
    {
        "id": 1,
        "name": "Lingua Express",
        "direction": ["english"],
        "district": "esil",
        "ages": [6, 7, 8, 9, 10, 11, 12, 13, 14],
        "price_min": 18000,
        "price_max": 28000,
        "address": "ул. Достык 13, ЖК Triumph Astana, оф. 205",
        "phone": "+7 700 123 4501",
        "whatsapp": "+7 700 123 4501",
        "schedule": "Пн, Ср, Пт 15:00–19:00 | Сб 10:00–15:00",
        "group_size": "8–10 человек",
        "trial": True,
        "verified_date": "01.07.2026",
        "description": "Cambridge-программа, подготовка к IELTS. Все уровни от A1.",
        "rating": 4.8,
        "reviews_count": 47,
    },
    {
        "id": 2,
        "name": "English World Kids",
        "direction": ["english"],
        "district": "esil",
        "ages": [4, 5, 6, 7, 8, 9, 10, 11],
        "price_min": 15000,
        "price_max": 22000,
        "address": "просп. Туран 7, ТЦ Asia Park, 3 этаж",
        "phone": "+7 701 234 5602",
        "whatsapp": "+7 701 234 5602",
        "schedule": "Вт, Чт 14:30–18:30 | Сб, Вс 09:00–13:00",
        "group_size": "6–8 человек",
        "trial": True,
        "verified_date": "02.07.2026",
        "description": "Игровая методика для детей 4–11 лет. Носитель языка по субботам.",
        "rating": 4.9,
        "reviews_count": 62,
    },
    {
        "id": 3,
        "name": "SpeakUp Center",
        "direction": ["english"],
        "district": "esil",
        "ages": [10, 11, 12, 13, 14, 15, 16],
        "price_min": 22000,
        "price_max": 35000,
        "address": "ул. Сыганак 14, Бизнес-центр Premium, оф. 312",
        "phone": "+7 702 345 6703",
        "whatsapp": "+7 702 345 6703",
        "schedule": "Пн–Пт 15:00–20:00 | Сб 10:00–16:00",
        "group_size": "5–7 человек",
        "trial": True,
        "verified_date": "01.07.2026",
        "description": "IELTS, SAT, разговорный. Для 10–16 лет. Подготовка к НИШ/БИЛ.",
        "rating": 4.7,
        "reviews_count": 38,
    },
    # ─────────── МАТЕМАТИКА ────────────────────────────────────
    {
        "id": 4,
        "name": "Олимп Математика",
        "direction": ["math"],
        "district": "esil",
        "ages": [6, 7, 8, 9, 10, 11, 12, 13, 14],
        "price_min": 16000,
        "price_max": 25000,
        "address": "ул. Иманбаевой 8, ЖК Capital, 1 этаж",
        "phone": "+7 703 456 7804",
        "whatsapp": "+7 703 456 7804",
        "schedule": "Пн, Ср, Пт 14:00–18:00 | Сб 10:00–14:00",
        "group_size": "8–12 человек",
        "trial": True,
        "verified_date": "03.07.2026",
        "description": "Подготовка к олимпиадам, ЕНТ, НИШ. Ментальная арифметика для млад. классов.",
        "rating": 4.6,
        "reviews_count": 53,
    },
    {
        "id": 5,
        "name": "FizMat Junior",
        "direction": ["math", "robotics"],
        "district": "esil",
        "ages": [9, 10, 11, 12, 13, 14],
        "price_min": 20000,
        "price_max": 32000,
        "address": "просп. Астана 18, ЖК Royal Triumph, оф. 108",
        "phone": "+7 704 567 8905",
        "whatsapp": "+7 704 567 8905",
        "schedule": "Вт, Чт, Сб 15:00–19:00",
        "group_size": "6–8 человек (практика 80%)",
        "trial": True,
        "verified_date": "02.07.2026",
        "description": "Физика + математика углублённо. Группы до 8 чел. Куратор для каждого.",
        "rating": 4.9,
        "reviews_count": 29,
    },
    {
        "id": 6,
        "name": "Абакус Центр",
        "direction": ["math"],
        "district": "esil",
        "ages": [5, 6, 7, 8, 9, 10, 11],
        "price_min": 14000,
        "price_max": 20000,
        "address": "ул. Сарыарка 3, ТРЦ Keruen, 2 этаж",
        "phone": "+7 705 678 9006",
        "whatsapp": "+7 705 678 9006",
        "schedule": "Пн, Ср, Пт 14:00–17:30 | Сб 10:00–13:00",
        "group_size": "8–10 человек",
        "trial": True,
        "verified_date": "03.07.2026",
        "description": "Ментальная арифметика на японских счётах абакус. 5–11 лет.",
        "rating": 4.7,
        "reviews_count": 41,
    },
    # ─────────── РОБОТОТЕХНИКА / IT ────────────────────────────
    {
        "id": 7,
        "name": "RoboLab Astana",
        "direction": ["robotics"],
        "district": "esil",
        "ages": [7, 8, 9, 10, 11, 12, 13, 14],
        "price_min": 22000,
        "price_max": 35000,
        "address": "ул. Достык 5, БЦ City Center, оф. 401",
        "phone": "+7 706 789 0107",
        "whatsapp": "+7 706 789 0107",
        "schedule": "Сб, Вс 10:00–14:00 | Пн, Ср 16:00–19:00",
        "group_size": "6–10 человек",
        "trial": True,
        "verified_date": "01.07.2026",
        "description": "LEGO, Arduino, Scratch, Python. Чемпионы WRO Kazakhstan 2024.",
        "rating": 4.9,
        "reviews_count": 71,
    },
    {
        "id": 8,
        "name": "CodeKids",
        "direction": ["robotics"],
        "district": "esil",
        "ages": [6, 7, 8, 9, 10, 11, 12, 13],
        "price_min": 18000,
        "price_max": 28000,
        "address": "просп. Туран 24, ЖК Expo boulevard, оф. 205",
        "phone": "+7 707 890 1208",
        "whatsapp": "+7 707 890 1208",
        "schedule": "Вт, Чт, Сб 15:00–18:30",
        "group_size": "8–12 человек",
        "trial": True,
        "verified_date": "04.07.2026",
        "description": "Программирование для детей 6–13. Scratch, Python, игровые проекты.",
        "rating": 4.6,
        "reviews_count": 33,
    },
    # ─────────── ТАНЦЫ ─────────────────────────────────────────
    {
        "id": 9,
        "name": "Dance Academy Astana",
        "direction": ["dance"],
        "district": "esil",
        "ages": [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
        "price_min": 15000,
        "price_max": 25000,
        "address": "ул. Жубанова 6, ТЦ Атлант, 2 этаж",
        "phone": "+7 708 901 2309",
        "whatsapp": "+7 708 901 2309",
        "schedule": "Пн, Ср, Пт 15:30–19:30 | Сб 10:00–14:00",
        "group_size": "10–15 человек",
        "trial": True,
        "verified_date": "02.07.2026",
        "description": "Хореография, хип-хоп, контемп. Конкурсы и выступления.",
        "rating": 4.7,
        "reviews_count": 58,
    },
    {
        "id": 10,
        "name": "Балет и Хореография Грация",
        "direction": ["dance"],
        "district": "esil",
        "ages": [4, 5, 6, 7, 8, 9, 10, 11, 12],
        "price_min": 18000,
        "price_max": 28000,
        "address": "ул. Сыганак 9, ЖК Prime Residence, оф. 102",
        "phone": "+7 709 012 3410",
        "whatsapp": "+7 709 012 3410",
        "schedule": "Вт, Чт, Сб 14:00–18:00",
        "group_size": "8–12 человек",
        "trial": True,
        "verified_date": "03.07.2026",
        "description": "Классический балет, народные танцы, хореография. Девочки и мальчики.",
        "rating": 4.8,
        "reviews_count": 44,
    },
    # ─────────── РИСОВАНИЕ / ИЗО ───────────────────────────────
    {
        "id": 11,
        "name": "ArtSpace Studio",
        "direction": ["art"],
        "district": "esil",
        "ages": [5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
        "price_min": 14000,
        "price_max": 22000,
        "address": "ул. Иманбаевой 14/2, 1 этаж",
        "phone": "+7 700 123 4511",
        "whatsapp": "+7 700 123 4511",
        "schedule": "Пн–Пт 14:00–19:00 | Сб 10:00–15:00",
        "group_size": "6–8 человек",
        "trial": True,
        "verified_date": "01.07.2026",
        "description": "Рисунок, живопись, скульптура, digital art. Выставки каждый квартал.",
        "rating": 4.8,
        "reviews_count": 36,
    },
    {
        "id": 12,
        "name": "Творческая Мастерская Акварель",
        "direction": ["art"],
        "district": "esil",
        "ages": [6, 7, 8, 9, 10, 11, 12],
        "price_min": 12000,
        "price_max": 18000,
        "address": "просп. Астана 35, ЖК Нурсат, 1 этаж",
        "phone": "+7 701 234 5612",
        "whatsapp": "+7 701 234 5612",
        "schedule": "Вт, Чт, Сб 14:00–17:30",
        "group_size": "8–10 человек",
        "trial": True,
        "verified_date": "04.07.2026",
        "description": "Акварель, масло, пастель, лепка. Маленькие группы, уютная студия.",
        "rating": 4.6,
        "reviews_count": 27,
    },
    # ─────────── СПОРТ ─────────────────────────────────────────
    {
        "id": 13,
        "name": "SportKids Есиль",
        "direction": ["sport"],
        "district": "esil",
        "ages": [4, 5, 6, 7, 8, 9, 10, 11, 12],
        "price_min": 12000,
        "price_max": 20000,
        "address": "ул. Туркестан 2, ТЦ MEGA Silk Way, спортзал B1",
        "phone": "+7 702 345 6713",
        "whatsapp": "+7 702 345 6713",
        "schedule": "Пн, Ср, Пт 14:00–18:00 | Сб, Вс 09:00–12:00",
        "group_size": "10–15 человек",
        "trial": True,
        "verified_date": "02.07.2026",
        "description": "Гимнастика, акробатика, спортивные игры. 4–12 лет. Тренеры с разрядом.",
        "rating": 4.5,
        "reviews_count": 49,
    },
    {
        "id": 14,
        "name": "Плавание AquaKids",
        "direction": ["sport"],
        "district": "esil",
        "ages": [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
        "price_min": 18000,
        "price_max": 30000,
        "address": "просп. Мəңгілік Ел 55, бассейн Astana Arena",
        "phone": "+7 703 456 7814",
        "whatsapp": "+7 703 456 7814",
        "schedule": "Пн–Пт 07:00–09:00 и 16:00–20:00 | Сб, Вс 09:00–13:00",
        "group_size": "4–6 человек",
        "trial": True,
        "verified_date": "01.07.2026",
        "description": "Плавание с 3 лет. Открытые и закрытые бассейны. Группы по уровням.",
        "rating": 4.7,
        "reviews_count": 88,
    },
    {
        "id": 15,
        "name": "Каратэ Shotokan",
        "direction": ["sport"],
        "district": "esil",
        "ages": [5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
        "price_min": 10000,
        "price_max": 16000,
        "address": "ул. Жубанова 3, Дворец спорта Казахстан, зал 2",
        "phone": "+7 704 567 8915",
        "whatsapp": "+7 704 567 8915",
        "schedule": "Пн, Ср, Пт 15:00–18:00 | Сб 10:00–12:00",
        "group_size": "12–20 человек",
        "trial": True,
        "verified_date": "03.07.2026",
        "description": "Сётокан каратэ. Тренер — Мастер спорта. Соревнования по всему Казахстану.",
        "rating": 4.6,
        "reviews_count": 62,
    },
    # ─────────── МУЗЫКА ────────────────────────────────────────
    {
        "id": 16,
        "name": "Музыкальная Студия До-Ре-Ми",
        "direction": ["music"],
        "district": "esil",
        "ages": [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
        "price_min": 15000,
        "price_max": 25000,
        "address": "ул. Достык 3/1, ЖК Grand Astana, оф. 201",
        "phone": "+7 705 678 9016",
        "whatsapp": "+7 705 678 9016",
        "schedule": "Пн–Пт 14:00–20:00 | Сб 10:00–16:00",
        "group_size": "Индивидуально или мини-группы 2-3",
        "trial": True,
        "verified_date": "02.07.2026",
        "description": "Фортепиано, гитара, вокал, скрипка. Подготовка к муз. школе.",
        "rating": 4.8,
        "reviews_count": 51,
    },
    {
        "id": 17,
        "name": "Guitar School Rock&Roll",
        "direction": ["music"],
        "district": "esil",
        "ages": [8, 9, 10, 11, 12, 13, 14, 15, 16],
        "price_min": 18000,
        "price_max": 28000,
        "address": "просп. Туран 47, 2 этаж",
        "phone": "+7 706 789 0117",
        "whatsapp": "+7 706 789 0117",
        "schedule": "Вт, Чт, Сб 14:00–20:00",
        "group_size": "Индивидуально / 2-4 чел.",
        "trial": True,
        "verified_date": "04.07.2026",
        "description": "Гитара (акустическая/электро), бас, барабаны, вокал. Собственная студия.",
        "rating": 4.7,
        "reviews_count": 34,
    },
    # ─────────── РАЗВИТИЕ (ОЗ2-МОСТ) ──────────────────────────
    {
        "id": 18,
        "name": "Шахматный клуб Magnus",
        "direction": ["development"],
        "district": "esil",
        "ages": [6, 7, 8, 9, 10, 11, 12, 13, 14],
        "price_min": 12000,
        "price_max": 18000,
        "address": "ул. Иманбаевой 7, ЖК Аэробус, 1 этаж",
        "phone": "+7 707 890 1218",
        "whatsapp": "+7 707 890 1218",
        "schedule": "Пн, Ср, Пт 15:00–18:30 | Сб 10:00–14:00",
        "group_size": "6–10 человек",
        "trial": True,
        "verified_date": "01.07.2026",
        "description": "Шахматы с нуля до разряда. Тренер — кандидат мастера спорта.",
        "rating": 4.8,
        "reviews_count": 43,
    },
    {
        "id": 19,
        "name": "Риторика и Лидерство",
        "direction": ["development"],
        "district": "esil",
        "ages": [8, 9, 10, 11, 12, 13, 14],
        "price_min": 16000,
        "price_max": 24000,
        "address": "просп. Мəңгілік Ел 11, ЖК Expo, конференц-зал 3",
        "phone": "+7 708 901 2319",
        "whatsapp": "+7 708 901 2319",
        "schedule": "Сб, Вс 10:00–14:00",
        "group_size": "8–12 человек",
        "trial": True,
        "verified_date": "03.07.2026",
        "description": "Публичные выступления, дебаты, мышление, лидерство. 8–14 лет.",
        "rating": 4.7,
        "reviews_count": 22,
    },
    {
        "id": 20,
        "name": "ÖZEN Pilot (подготовительная группа)",
        "direction": ["development"],
        "district": "esil",
        "ages": [8, 9, 10, 11, 12, 13, 14],
        "price_min": 0,
        "price_max": 0,
        "address": "ул. Кенесары 4, офис Dana Abiltayeva",
        "phone": "+7 700 OZEN OZI",
        "whatsapp": "+7 700 000 0001",
        "schedule": "По записи",
        "group_size": "Индивидуально",
        "trial": True,
        "verified_date": "04.07.2026",
        "description": "🎯 БЕСПЛАТНО: Пробный профиль развития вашего ребёнка от ÖZEN. Навигатор потенциала. Не тест — гипотеза для исследования.",
        "rating": 5.0,
        "reviews_count": 5,
    },
]

DIRECTIONS = {
    "english":     ("🇬🇧 Английский язык", "english"),
    "math":        ("📐 Математика", "math"),
    "robotics":    ("🤖 Робототехника / IT", "robotics"),
    "dance":       ("💃 Танцы / Хореография", "dance"),
    "art":         ("🎨 Рисование / ИЗО", "art"),
    "sport":       ("🏊 Спорт", "sport"),
    "music":       ("🎵 Музыка", "music"),
    "development": ("🧠 Развитие / Шахматы", "development"),
}

DISTRICTS = {
    "esil":         "🏙 Есиль",
    "almatinskiy":  "🏘 Алматинский",
    "baikonur":     "🏗 Байконур",
    "nura":         "🌿 Нура",
    "any":          "🗺 Любой район",
}

AGE_GROUPS = {
    "4-6":   (4, 6,  "👶 4–6 лет"),
    "7-10":  (7, 10, "🧒 7–10 лет"),
    "11-14": (11, 14, "👦 11–14 лет"),
    "15+":   (15, 18, "👨‍🎓 15+ лет"),
}

BUDGETS = {
    "low":    (0,     15000,  "💚 до 15 000 ₸"),
    "medium": (15001, 25000,  "💛 15 000–25 000 ₸"),
    "high":   (25001, 40000,  "🟠 25 000–40 000 ₸"),
    "any":    (0,     999999, "💜 Любой бюджет"),
}

def search_centers(direction=None, age=None, district=None, budget_key=None):
    results = CENTERS[:]
    if direction and direction != "any":
        results = [c for c in results if direction in c["direction"]]
    if age is not None:
        results = [c for c in results if c["ages"][0] <= age <= c["ages"][-1]]
    if district and district != "any":
        results = [c for c in results if c["district"] == district]
    if budget_key and budget_key != "any":
        bmin, bmax, _ = BUDGETS[budget_key]
        results = [c for c in results if c["price_min"] <= bmax and c["price_max"] >= bmin]
    results.sort(key=lambda x: -x["rating"])
    return results[:10]

# ─── НОВЫЕ ПОЛЯ КАРТОЧКИ (заполнять по мере верификации) ───
# В любой центр можно добавить строки — бот покажет их автоматически:
#   "languages": "рус / каз / англ",
#   "instagram": "https://instagram.com/имя_центра",
#   "link_2gis": "https://2gis.kz/astana/firm/...",
#   "website":   "https://сайт-центра.kz",
# Если поля нет или оно пустое — строка в карточке просто не появится.

def format_center_card(c):
    stars = "⭐" * round(c["rating"])
    price_str = (
        f"🆓 БЕСПЛАТНО" if c["price_max"] == 0
        else f"💰 {c['price_min']:,} – {c['price_max']:,} ₸/мес"
    )
    trial_str = "✅ Есть пробное занятие" if c["trial"] else "❌ Пробного нет"
    return (
        f"━━━━━━━━━━━━━━━━━━━━━━\n"
        f"🏫 *{c['name']}*\n"
        f"{stars} {c['rating']} ({c['reviews_count']} отзывов)\n\n"
        f"{price_str}\n"
        f"📌 {c['address']}\n"
        f"📅 {c['schedule']}\n"
        f"👥 Группа: {c['group_size']}\n"
        f"{trial_str}\n"
        + (f"🗣 Языки: {c['languages']}\n" if c.get("languages") else "")
        + (f"📸 Instagram: {c['instagram']}\n" if c.get("instagram") else "")
        + (f"🗺 2ГИС: {c['link_2gis']}\n" if c.get("link_2gis") else "")
        + (f"🌐 Сайт: {c['website']}\n" if c.get("website") else "")
        + f"\n💬 {c['description']}\n"
        f"🔄 Верифицировано: {c['verified_date']}"
    )
